import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SkySpectra",
  description: "Generated by create next app",
  // openGraph: {
  //   type: "website",
  //   url: "https://example.com",
  //   title: "My Website",
  //   description: "My Website Description",
  //   siteName: "My Website",
  //   images: [{
  //     url: "https://example.com/og.png",
  //   }],
  // }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
